// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/login" | "/register";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/_auth.register.tsx": {
    id: "routes/_auth.register";
    page: "/register";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/_auth.register": typeof import("./app/routes/_auth.register.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};